---
- name: install mysql client on all hosts
  hosts: all
  user: vagrant
  sudo: yes

  roles:
    - common


- name: configure and deploy the webservers and application code
  hosts: web1, web2
  user: vagrant
  sudo: yes

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: db1
  user: vagrant
  sudo: yes

  roles:
    - database
